#!/usr/bin/env bash
#
# Generate (or surface) a Stellar account for deploying Pesalo contracts.
#
# Behaviour
#   * If the named CLI identity exists, prints its address and reuses it.
#   * Otherwise generates a fresh keypair in the stellar CLI's local store.
#   * On testnet, funds the account via friendbot (one-time, idempotent).
#   * Writes the deployer's address to contracts/.deployer.env so the
#     downstream deploy / initialize / seed scripts pick it up automatically.
#
# Usage
#   ./scripts/create-deployer-wallet.sh [identity-name]
#
# Environment
#   SOROBAN_NETWORK  network alias (default: testnet)

set -euo pipefail

NAME="${1:-pesalo-deployer}"
NETWORK="${SOROBAN_NETWORK:-testnet}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEPLOYER_ENV="$ROOT_DIR/contracts/.deployer.env"

command -v stellar >/dev/null 2>&1 || {
  echo "Stellar CLI not found. Install: cargo install --locked stellar-cli" >&2
  exit 1
}

# Configure network alias if it isn't already (idempotent — stellar CLI
# emits a no-op when the alias matches what's already stored).
if [[ "$NETWORK" == "testnet" ]]; then
  stellar network add testnet \
    --rpc-url https://soroban-testnet.stellar.org \
    --network-passphrase "Test SDF Network ; September 2015" \
    2>/dev/null || true
fi

# Generate the key if it doesn't already exist.
if stellar keys ls 2>/dev/null | awk '{print $1}' | grep -qx "$NAME"; then
  ADDRESS=$(stellar keys address "$NAME")
  echo "[wallet] reusing existing identity '$NAME' → $ADDRESS"
else
  echo "[wallet] generating new identity '$NAME' on $NETWORK"
  if [[ "$NETWORK" == "testnet" ]]; then
    stellar keys generate "$NAME" --network "$NETWORK" --fund
  else
    stellar keys generate "$NAME" --network "$NETWORK"
    echo "[wallet] WARNING: identity created but not funded — fund it manually before deploying."
  fi
  ADDRESS=$(stellar keys address "$NAME")
fi

mkdir -p "$ROOT_DIR/contracts"
cat > "$DEPLOYER_ENV" <<EOF
# Generated by scripts/create-deployer-wallet.sh — safe to commit.
# (The private key lives in the Stellar CLI's local store, not in this file.)
STELLAR_ACCOUNT=$NAME
SOROBAN_NETWORK=$NETWORK
DEPLOYER_ADDRESS=$ADDRESS
EOF

echo ""
echo "Deployer ready:"
echo "  identity : $NAME"
echo "  address  : $ADDRESS"
echo "  network  : $NETWORK"
echo "  env file : $DEPLOYER_ENV"
echo ""
echo "Run the deploy pipeline:"
echo "  source $DEPLOYER_ENV"
echo "  ./scripts/deploy-contracts.sh"
echo "  ./scripts/initialize-protocol.sh"
echo "  ./scripts/seed-liquidity.sh"
