#!/usr/bin/env bash
#
# Create test USDC + EURC Stellar Asset Contracts on testnet.
#
# On real testnet Circle does not issue USDC, so for end-to-end protocol
# testing we create our own issuer and wrap "USDC" + "EURC" assets under it.
# These wrapped SAC contracts are functionally identical to the real
# USDC/EURC SACs on mainnet — same Token interface, same Soroban semantics.
#
# Outputs the SAC contract IDs into contracts/.assets.env which the deploy
# pipeline auto-sources.
#
# Required env:
#   SOROBAN_NETWORK  network alias (default: testnet)

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ASSETS_ENV="$ROOT_DIR/contracts/.assets.env"
DEPLOYER_ENV="$ROOT_DIR/contracts/.deployer.env"
NETWORK="${SOROBAN_NETWORK:-testnet}"

if [[ -f "$DEPLOYER_ENV" ]]; then
  # shellcheck disable=SC1090
  source "$DEPLOYER_ENV"
fi

if [[ -z "${STELLAR_ACCOUNT:-}" ]]; then
  echo "Run ./scripts/create-deployer-wallet.sh first." >&2
  exit 1
fi

# Create (or reuse) a dedicated issuer identity so the issuing account stays
# separate from the deployer / liquidity-provider account.
ISSUER_NAME="pesalo-asset-issuer"
if stellar keys ls 2>/dev/null | awk '{print $1}' | grep -qx "$ISSUER_NAME"; then
  ISSUER_ADDRESS=$(stellar keys address "$ISSUER_NAME")
  echo "[assets] reusing existing issuer '$ISSUER_NAME' → $ISSUER_ADDRESS"
else
  echo "[assets] generating new issuer identity"
  stellar keys generate "$ISSUER_NAME" --network "$NETWORK" --fund
  ISSUER_ADDRESS=$(stellar keys address "$ISSUER_NAME")
fi

deploy_asset() {
  local code="$1"
  local asset_str="${code}:${ISSUER_ADDRESS}"

  # contract asset deploy is idempotent — if the SAC is already deployed,
  # it returns the existing contract ID.
  local cid
  cid=$(stellar contract asset deploy \
    --asset "$asset_str" \
    --source-account "$STELLAR_ACCOUNT" \
    --network "$NETWORK" 2>/dev/null || true)

  if [[ -z "$cid" ]]; then
    cid=$(stellar contract id asset \
      --asset "$asset_str" \
      --network "$NETWORK" 2>/dev/null | tail -1)
  fi

  echo "[assets] $code SAC: $cid" >&2
  echo "$cid"
}

USDC_ASSET=$(deploy_asset "USDC")
EURC_ASSET=$(deploy_asset "EURC")

cat > "$ASSETS_ENV" <<EOF
# Generated by scripts/create-test-assets.sh
ISSUER_ACCOUNT=$ISSUER_NAME
ISSUER_ADDRESS=$ISSUER_ADDRESS
USDC_ASSET_CONTRACT_ID=$USDC_ASSET
EURC_ASSET_CONTRACT_ID=$EURC_ASSET
EOF

echo ""
echo "Test assets ready:"
echo "  issuer     : $ISSUER_ADDRESS"
echo "  USDC SAC   : $USDC_ASSET"
echo "  EURC SAC   : $EURC_ASSET"
echo "  env file   : $ASSETS_ENV"
