#!/usr/bin/env bash
#
# Upload kalepail's smart-wallet Soroban contract to testnet so the mobile
# passkey-kit SDK can use its hash when deploying per-user smart wallets.
#
# Why no factory?
#   passkey-kit's `createWallet()` calls `PasskeyClient.deploy(wasmHash, …)`
#   directly. The on-chain "factory" pattern (a separate contract that owns
#   the install step) was retired in favour of using the Soroban deploy
#   operation with constructor arguments. We only need the wallet's WASM
#   uploaded; the SDK does the per-user deploy from a deterministic source
#   account each time someone signs up.
#
# Note: passkey-kit's README flags itself as legacy. For mainnet we should
# migrate to OpenZeppelin Smart Accounts via @smart-account-kit/sdk.
#
# Required env (auto-sourced from contracts/.deployer.env):
#   STELLAR_ACCOUNT    funded source account for the upload tx
#   SOROBAN_NETWORK    network alias (default: testnet)
#
# Optional env:
#   PASSKEY_KIT_REPO   override the kalepail/passkey-kit git URL
#   PASSKEY_KIT_REF    branch/tag to check out (default: main)

set -euo pipefail

# Force rustup-managed toolchain.
if [[ -d "$HOME/.cargo/bin" ]]; then
  export PATH="$HOME/.cargo/bin:$PATH"
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# Keep the clone outside the Pesalo contracts/ tree so its Cargo workspace
# is self-contained — otherwise `stellar contract build` walks up to our
# workspace toml and builds the wrong crates.
CACHE_DIR="$ROOT_DIR/.cache/external"
REPO_DIR="$CACHE_DIR/passkey-kit"
DEPLOYER_ENV="$ROOT_DIR/contracts/.deployer.env"
PASSKEY_ENV="$ROOT_DIR/contracts/.passkey.env"

REPO_URL="${PASSKEY_KIT_REPO:-https://github.com/kalepail/passkey-kit.git}"
REPO_REF="${PASSKEY_KIT_REF:-next}"

if [[ -f "$DEPLOYER_ENV" ]]; then
  # shellcheck disable=SC1090
  source "$DEPLOYER_ENV"
fi

NETWORK="${SOROBAN_NETWORK:-testnet}"
SOURCE_ACCOUNT="${STELLAR_ACCOUNT:-}"

if [[ -z "$SOURCE_ACCOUNT" ]]; then
  echo "STELLAR_ACCOUNT not set. Run ./scripts/create-deployer-wallet.sh first." >&2
  exit 1
fi

for tool in stellar git jq cargo rustup; do
  command -v "$tool" >/dev/null 2>&1 || {
    echo "missing required tool: $tool" >&2
    exit 1
  }
done

mkdir -p "$CACHE_DIR"

if [[ -d "$REPO_DIR/.git" ]]; then
  echo "[passkey] updating local clone of $REPO_URL"
  git -C "$REPO_DIR" fetch --depth 1 origin "$REPO_REF" >/dev/null
  git -C "$REPO_DIR" checkout --quiet "$REPO_REF"
  git -C "$REPO_DIR" reset --hard "origin/$REPO_REF" >/dev/null
else
  echo "[passkey] cloning $REPO_URL@$REPO_REF"
  git clone --depth 1 --branch "$REPO_REF" "$REPO_URL" "$REPO_DIR"
fi

# Locate the smart-wallet contract crate.
WALLET_CRATE=""
for candidate in \
  "smart-wallet" \
  "webauthn-wallet" \
  "passkey-wallet"; do
  if [[ -f "$REPO_DIR/contracts/$candidate/Cargo.toml" ]]; then
    WALLET_CRATE="$candidate"
    break
  fi
done

if [[ -z "$WALLET_CRATE" ]]; then
  echo "Could not locate the smart-wallet crate inside $REPO_DIR" >&2
  echo "Repository layout:" >&2
  find "$REPO_DIR/contracts" -maxdepth 2 -name "Cargo.toml" >&2 || true
  exit 1
fi

echo "[passkey] building contracts/$WALLET_CRATE"
rustup target add wasm32v1-none >/dev/null 2>&1 || true
# Run from the passkey-kit contracts/ workspace so stellar contract build
# uses its own Cargo workspace, not ours.
(
  cd "$REPO_DIR/contracts"
  stellar contract build --profile release --package "$WALLET_CRATE"
)

# Find the produced wasm. The output name is the crate name with hyphens
# converted to underscores.
CRATE_NAME=$(grep -E '^name\s*=' "$REPO_DIR/contracts/$WALLET_CRATE/Cargo.toml" | head -1 | sed -E 's/.*"([^"]+)".*/\1/')
WASM_NAME=$(echo "$CRATE_NAME" | tr '-' '_')
WASM_PATH="$REPO_DIR/contracts/target/wasm32v1-none/release/${WASM_NAME}.wasm"

if [[ ! -f "$WASM_PATH" ]]; then
  echo "Expected wasm at $WASM_PATH not found" >&2
  find "$REPO_DIR/target/wasm32v1-none/release" -name "*.wasm" >&2 || true
  exit 1
fi

echo "[passkey] uploading smart wallet wasm to $NETWORK"
WALLET_HASH=$(stellar contract upload \
  --wasm "$WASM_PATH" \
  --source-account "$SOURCE_ACCOUNT" \
  --network "$NETWORK" 2>/dev/null | tail -1)

if [[ -z "$WALLET_HASH" ]]; then
  echo "Upload returned empty hash" >&2
  exit 1
fi

echo "[passkey] wallet wasm hash: $WALLET_HASH"

# Persist for downstream scripts + the mobile app build.
cat > "$PASSKEY_ENV" <<EOF
# Generated by scripts/deploy-passkey-wallet.sh
PASSKEY_WALLET_WASM_HASH=$WALLET_HASH
PASSKEY_WALLET_CRATE=$CRATE_NAME
PASSKEY_WALLET_SOURCE=$REPO_URL@$REPO_REF
EOF

echo ""
echo "Passkey smart-wallet ready:"
echo "  source     : $REPO_URL@$REPO_REF"
echo "  crate      : $CRATE_NAME"
echo "  wasm hash  : $WALLET_HASH"
echo "  env file   : $PASSKEY_ENV"
echo ""
echo "Add to mobile/.env.local:"
echo "  EXPO_PUBLIC_PASSKEY_WALLET_HASH=$WALLET_HASH"
